name: Bug report
description: Report a problem with the Retro Indie Josh website
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the project. Fill out the info below.
  - type: input
    id: summary
    attributes:
      label: Short summary
      description: What went wrong?
      placeholder: Something isn't working correctly...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, device, or OS details
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Links, screenshots, etc.
